// ===== Conteúdo dos módulos =====
// Cada módulo tem um número, título, descrição curta (mostrada na trilha)
// e uma lista de "temas" (os antigos "sub-módulos"). Cada tema tem seu
// próprio título, descrição curta e "paragrafos" (o texto detalhado da
// página dele). Por enquanto os parágrafos estão com lorem ipsum — quando
// tiver o texto real de um tema, é só trocar o array "paragrafos" dele,
// um parágrafo por item, sem afetar os outros temas.
const dadosModulos = [
  {
    numero: 1,
    titulo: "Primeiros passos",
    descricao: "Ligar a tela, tocar e reconhecer os ícones",
    temas: [
      {
        titulo: "Como ligar",
        descricao: "Encontrando e apertando o botão certo",
        paragrafos: [
          "1. Encontre o botão de ligar",
          "Procure nas laterais do celular um botão chamado botão de energia ou botão de ligar e desligar. Na maioria dos celulares, ele fica na lateral direita. Geralmente é um botão comprido e separado dos botões de aumentar e diminuir o volume.", 
          "2. Aperte e segure o botão",
          "Depois de encontrar o botão, coloque o dedo sobre ele e aperte e segure por alguns segundos. Não é necessário apertar com força. Apenas mantenha o botão pressionado. Após alguns segundos, a tela deverá acender e aparecerá o nome ou o símbolo da marca do celular.Após alguns segundos, a tela deverá acender e aparecerá o nome ou o símbolo da marca do celular.",
          "3. Espere o celular iniciar",
          "Depois que a tela acender, não aperte nenhum botão. O celular precisa de alguns segundos para iniciar. Espere até aparecer a tela principal ou a tela que pede a senha. Esse processo pode demorar um pouco, principalmente se o celular estiver desligado há bastante tempo.",
          "4. Desbloqueie o celular",
          "Quando o celular terminar de ligar, pode aparecer uma tela pedindo para você deslizar o dedo pela tela. Faça o movimento indicado na tela. Depois, o celular poderá pedir uma senha, desenho, impressão digital ou reconhecimento facial. Digite sua senha ou use o método de desbloqueio que você costuma utilizar.",
          "Pronto! Seu celular está ligado e pronto para ser usado. 📱"
        ],
      },
      {
        titulo: "Como desligar",
        descricao: "Desligando o celular com segurança",
        paragrafos: [
          "1. Encontre o botão de ligar e desligar\nProcure o botão de energia na lateral do celular. É o mesmo botão que usamos para ligar o aparelho.\nNa maioria dos celulares, ele fica na lateral direita.",
          "2. Aperte e segure o botão\nColoque o dedo sobre o botão e aperte e segure por alguns segundos.\nDepois de um momento, aparecerá um menu na tela com algumas opções.\nProcure pela opção “Desligar”.",
          "3. Toque em “Desligar”\nQuando encontrar a opção “Desligar”, toque nela uma vez.\nO celular poderá perguntar novamente se você realmente deseja desligá-lo.\nSe isso acontecer, toque novamente em “Desligar” para confirmar.",
          "4. Espere a tela apagar\nDepois de confirmar, a tela ficará escura e o celular será desligado.",
          "Pronto! O celular está desligado. 📱",
        ],
      },
    {
      titulo: "Tocar, arrastar e segurar",
      descricao: "Aprendendo os toques básicos na tela",
      paragrafos: [
        "👆 1. \nTocar significa encostar o dedo na tela e tirá-lo logo em seguida.\nÉ como dar um pequeno toque na tela.\nUsamos o toque para abrir aplicativos, selecionar opções, apertar botões e escolher itens.\nExemplo:\nSe você quiser abrir o aplicativo do WhatsApp, procure o ícone do WhatsApp e toque uma vez nele.",
        "☝️ 2. \nArrastar significa colocar o dedo na tela e, sem tirá-lo, movê-lo para outro lugar.\nPor exemplo, para descer uma página:\n1. Coloque o dedo na tela.\n2. Mantenha o dedo encostado.\n3. Mova o dedo de baixo para cima.\n4. Só então tire o dedo da tela.\nEsse movimento é usado para passar pelas páginas, ver mais informações ou mover objetos na tela.",
        "👆 3. \nSegurar é parecido com tocar, mas existe uma diferença: em vez de tirar o dedo rapidamente, você mantém o dedo encostado na tela por alguns segundos.\nDepois de um momento, alguma coisa pode acontecer.\nPor exemplo, ao segurar o dedo sobre um aplicativo, podem aparecer algumas opções.\nPara fazer isso:",
        "\n3.1. Coloque o dedo sobre o item.",
        "\n3.2. Não mova o dedo.",
        "\n3.3. Mantenha-o encostado por alguns segundos.",
        "\n3.4. Quando aparecer uma opção ou o celular responder, tire o dedo.",
      ],
    },
      {
        titulo: "Encontrando os Ícones",
        descricao: "Onde ficam os aplicativos na tela",
        paragrafos: [
          "Os ícones são os pequenos desenhos que aparecem na tela do celular. Cada ícone representa um aplicativo ou uma função do aparelho.\nPor exemplo, o ícone do WhatsApp representa o aplicativo usado para enviar mensagens, enquanto o ícone de uma câmera abre a câmera do celular.",
          "📱 Onde ficam os ícones?\nQuando você desbloqueia o celular, normalmente aparece a tela inicial. Nela, você encontrará vários ícones organizados pela tela.\nAlguns aplicativos podem estar diretamente na tela inicial. Outros podem estar em uma lista com todos os aplicativos instalados.",
          "👆 Como abrir um aplicativo?\nPara abrir um aplicativo, primeiro encontre o ícone que deseja usar. Depois:\n1. Procure o desenho do aplicativo na tela.\n2. Toque uma vez sobre o ícone.\n3. Aguarde alguns instantes.\n4. O aplicativo será aberto.\nPor exemplo, para abrir o WhatsApp, procure o ícone do WhatsApp e toque uma vez sobre ele.",
          "🔎 E se eu não encontrar o aplicativo?\nNão se preocupe. O aplicativo pode estar em outra tela.\nVocê pode arrastar o dedo para a esquerda ou para a direita para mudar de tela e procurar o ícone.\nTambém é possível abrir a lista de aplicativos do celular. Em muitos aparelhos, basta arrastar o dedo de baixo para cima na tela inicial.",
          "💡 Dica: Não precisa decorar onde cada aplicativo está. Com o tempo, você vai começar a reconhecer os ícones e saber onde encontrá-los.",
          "🧠 Lembre-se\nÍcone = desenho que representa um aplicativo ou função. Por exemplo:",
          "💬 WhatsApp: mensagens e chamadas.",
          "📷 Câmera: tirar fotos e gravar vídeos.",
          "☎️ Telefone: fazer ligações.",
          "⚙️ Configurações: alterar as opções do celular.",
          "🌐 Internet: acessar sites e páginas da internet.",
        ],
      },
    ],
  },
  {
    numero: 2,
    titulo: "Conversas e chamadas",
    descricao: "Mandar mensagem e ligar para a família",
    temas: [
      {
        titulo: "Enviando uma mensagem",
        descricao: "Escrevendo e mandando um texto pelo WhatsApp",
        paragrafos: [
          "O WhatsApp permite que você converse com familiares e amigos enviando mensagens de texto pelo celular. Vamos aprender passo a passo como escrever e enviar uma mensagem.",
          "1. Primeiro abra o WhatsApp\n. Procure o ícone do WhatsApp na tela do celular. O ícone é verde e possui o desenho de um telefone dentro de um balão de conversa. Depois de encontrá-lo, toque uma vez sobre o ícone para abrir o aplicativo.",
          "2. Escolha uma pessoa.\n Procure pelo nome da pessoa para quem deseja enviar a mensagem e toque sobre ela. Se você ainda não tiver uma conversa com essa pessoa, procure o botão para iniciar uma nova conversa e escolha o contato desejado.",
          "3. Escreva a mensagem.\nDepois de abrir a conversa, aparecerá uma área na parte de baixo da tela para escrever. Toque nessa área para abrir o teclado. Agora, digite a mensagem que deseja enviar. Por exemplo: \"Olá, filho! Como você está?\" Não tenha pressa para escrever. Você pode apagar uma letra ou palavra caso tenha cometido algum erro.",
          "4. Envie a mensagem.\nQuando terminar de escrever, procure o botão de enviar, que geralmente aparece como uma seta ao lado do campo onde você escreveu. Toque nesse botão uma vez. A mensagem será enviada e aparecerá dentro da conversa.",
          "💡 Dica\nSe você perceber que escreveu alguma coisa errada, não precisa apagar a mensagem inteira. Você pode tocar no local onde está o erro e usar o teclado para corrigir. E lembre-se: não é necessário apertar a tela com força. Um toque leve já é suficiente.",
          "🧠 Vamos lembrar?\nAbrir → escolher a pessoa → escrever → enviar. É só seguir esses quatro passos para conversar com seus familiares e amigos pelo WhatsApp.",
        ],
      },
      {
        titulo: "Fazendo uma ligação",
        descricao: "Chamando alguém pelo celular",
        paragrafos: [
          "Além de enviar mensagens, o WhatsApp também permite que você faça ligações para conversar com familiares e amigos. A ligação é feita pela internet, por isso é necessário estar conectado ao Wi-Fi ou aos dados móveis.",
          "📞 1. Abra o WhatsApp\nPrimeiro, procure o ícone do WhatsApp na tela do celular. Toque uma vez sobre ele para abrir o aplicativo.",
          "👤 2. Primeiro procure a pessoa para quem deseja ligar. Você pode tocar sobre uma conversa que já existe ou procurar o contato na lista de conversas.",
          "📱 3. Toque no botão de ligação\nDepois de abrir a conversa (procure o ícone de um telefone 📞), que normalmente fica na parte de cima da tela. Toque uma vez sobre ele. O WhatsApp começará a fazer a ligação.",
          "🗣️ 4. Espere a pessoa atender.\n Enquanto a ligação estiver sendo realizada, você verá na tela que o WhatsApp está chamando a pessoa. Aguarde até que ela atenda. Quando ela atender, você poderá conversar normalmente.",
          "🔴 5. Como encerrar a ligação? \nQuando terminar a conversa, procure o botão vermelho com o símbolo de um telefone. Toque nele para encerrar a ligação. A chamada será finalizada.",
          "💡 Dica\nDurante a ligação, evite cobrir o microfone do celular com a mão. Fale normalmente, mantendo o celular próximo ao rosto.",
          "🧠 Vamos lembrar?\nAbrir o WhatsApp → escolher a pessoa → tocar no telefone 📞 → esperar atender → conversar → tocar no botão vermelho para desligar.",
        ],
      },
      {
        titulo: "Chamada de vídeo",
        descricao: "Vendo e sendo visto na tela",
        paragrafos: [
          "Além de enviar mensagens e fazer ligações, o WhatsApp também permite fazer chamadas de vídeo. Com uma chamada de vídeo, você pode conversar com uma pessoa e vê-la pela tela do celular, mesmo que ela esteja longe.",
          "Para fazer uma chamada de vídeo, é necessário estar conectado à internet, seja pelo Wi-Fi ou pelos dados móveis.",
          "📱 1. Abra o WhatsApp\nPrimeiro, procure o ícone do WhatsApp na tela do celular. Toque uma vez sobre ele para abrir o aplicativo.",
          "👤 2. Escolha uma pessoa\nProcure a pessoa com quem deseja fazer a chamada de vídeo. Você pode tocar em uma conversa que já existe ou procurar o contato na lista de conversas.",
          "🎥 3. Toque no botão de vídeo\nDepois de abrir a conversa, procure o ícone de uma câmera de vídeo 🎥, geralmente localizado na parte de cima da tela. Toque uma vez sobre ele. O WhatsApp começará a fazer a chamada de vídeo.",
          "⏳ 4. Espere a pessoa atender\nAguarde enquanto o celular chama a outra pessoa. Quando ela atender, a câmera será ativada e vocês poderão ver um ao outro durante a conversa. Procure deixar o celular em uma posição em que seu rosto fique bem visível.",
          "📞 5. Durante a chamada\nDurante a chamada de vídeo, alguns botões podem aparecer na tela. Você poderá:",,
          "🎤 5.1 Microfone: ligar ou desligar o seu microfone.",
          "🎥 5.2 Câmera: ligar ou desligar a sua câmera.",
          "🔴 6. Como encerrar a chamada\nQuando terminar de conversar, procure o botão vermelho com o símbolo de um telefone. Toque nele para encerrar a chamada.",
          "💡 Dica\nSe a outra pessoa não atender, não significa que o celular está com problema. Ela pode estar ocupada, sem internet ou simplesmente não ter visto a chamada.",
          "🧠 Vamos lembrar?\nAbrir o WhatsApp → escolher a pessoa → tocar na câmera 🎥 → esperar atender → conversar → tocar no botão vermelho para desligar.",
        ],
      },
      {
        titulo: "Áudios",
        descricao: "Gravando e ouvindo uma mensagem de voz",
        paragrafos: [
          "O WhatsApp também permite enviar mensagens de voz, também conhecidas como áudios. Elas são úteis quando você quer conversar, mas não quer ou não consegue digitar uma mensagem.",
          "Você pode gravar sua própria voz e enviar para outra pessoa. Também pode ouvir os áudios que receber.",
          "🎙️ 1. Abra uma conversa\nPrimeiro, abra o WhatsApp e escolha a pessoa para quem deseja enviar o áudio. Toque sobre o nome ou a conversa dessa pessoa.",
          "🎤 2. Encontre o botão do microfone\nNa parte de baixo da conversa, onde você escreve as mensagens, procure o símbolo de um microfone 🎤. Esse botão é usado para gravar sua voz.",
          "⏺️ 3. Grave o áudio\nPara começar a gravar:\n",
          "3.1. Toque e segure o botão do microfone.\n",
          "3.2. Enquanto estiver segurando, fale sua mensagem.\n",
          "3.3. Quando terminar de falar, solte o botão.\nO áudio será enviado automaticamente depois que você soltar o botão.",
          "💡 Dica\nFale de maneira clara e em um volume normal. Não é necessário colocar a boca muito perto do celular.",
          "🗑️ E se eu mudar de ideia?\nSe você estiver gravando e decidir que não quer enviar o áudio, não solte o botão. Enquanto estiver segurando o microfone, arraste o dedo para o lado indicado para cancelar a gravação. Assim, o áudio será apagado em vez de enviado.",
          "🔊 Como ouvir um áudio recebido?\nQuando alguém enviar um áudio para você, ele aparecerá dentro da conversa. Para ouvir:\n",
          "1. Procure a mensagem de voz.\n",
          "2. Toque no botão de reproduzir ▶️.\n",
          "3. O áudio começará a tocar.\n",
          "4. Você poderá ouvir a mensagem até o final.\n","Se quiser ouvir novamente, basta tocar no botão de reprodução outra vez.",
          "💡 Dica\nSe o som estiver muito baixo, verifique o volume do celular usando os botões de volume na lateral.",
          "🧠 Vamos lembrar?\nPara enviar: Segurar o microfone 🎤 → falar → soltar → áudio enviado.\nPara ouvir: Tocar no botão ▶️ → ouvir a mensagem.",
        ],
      },
    ],
  },
  {
    numero: 3,
    titulo: "Fotos e câmera",
    descricao: "Tirar, ver e enviar fotos dos netos",
    temas: [
      {
        titulo: "Tirando uma foto",
        descricao: "Usando a câmera do celular",
        paragrafos: [
          "O celular também pode ser usado para tirar fotos. Com a câmera, você pode registrar momentos importantes, como uma reunião de família, uma viagem, um aniversário ou simplesmente algo que queira guardar.",
          "Vamos aprender passo a passo como tirar uma foto.",
          "📷 1. Abra a câmera\nPrimeiro, procure o aplicativo Câmera 📷 na tela do celular. Toque uma vez sobre o ícone para abrir a câmera. Ao abrir, você verá na tela a imagem que está sendo captada pela câmera. Essa imagem mostra o que será fotografado.",
          "👀 2. Escolha o que deseja fotografar.\nAponte o celular para a pessoa, objeto ou lugar que deseja fotografar. Olhe para a tela e tente deixar aquilo que deseja fotografar dentro da imagem. Por exemplo, se quiser tirar uma foto de uma pessoa, tente deixar o rosto dela bem visível na tela.",
          "💡 Dica\nSegure o celular com as duas mãos para deixá-lo mais firme e evitar que a foto fique tremida.",
          "🎯 3. Enquadre a foto.\nEnquadrar significa escolher como aquilo que você quer fotografar ficará dentro da tela. Você pode mover o celular um pouco para cima, para baixo, para os lados ou para frente até encontrar uma posição que goste. Não tenha pressa. Você pode olhar a tela antes de tirar a foto.",
          "🔘 4. Aperte o botão de tirar foto.\nQuando estiver satisfeito com a imagem, procure o botão redondo da câmera, geralmente localizado na parte inferior da tela. Toque uma vez nesse botão. O celular fará um pequeno som ou mostrará uma animação, indicando que a foto foi tirada.",
          "🖼️ 5. Veja a foto.\nDepois de tirar a foto, procure a miniatura da imagem, geralmente localizada em um dos cantos da tela. Toque nela para abrir e ver a foto que acabou de tirar. Se não gostar da foto, você poderá apagá-la. Se gostar, ela ficará guardada no aplicativo de Fotos ou Galeria do celular.",
          "💡 Dica\nAntes de tirar a foto, limpe a lente da câmera com um pano macio se ela estiver suja. Uma lente suja pode deixar a imagem embaçada.",
          "🧠 Vamos lembrar?\nAbrir a câmera → apontar para o que deseja fotografar → enquadrar → tocar no botão da câmera 🔘 → ver a foto.",
          "📷 Pronto! Agora você já sabe como tirar uma foto usando o celular.",
        ],
      },
      {
        titulo: "Gravando um vídeo",
        descricao: "Guardando um momento em vídeo",
        paragrafos: [
          "Gravar um vídeo no celular é simples e permite registrar momentos especiais ou conversar com parentes e amigos. Acompanhe o passo a passo abaixo para aprender a gravar com clareza e segurança! 😉",
          "1. Abra o aplicativo da Câmera 📱.\nProcure o ícone de uma câmera fotográfica na tela principal do celular e toque nele uma vez para abrir.",
          "2. Mude para o modo Vídeo 🎥.\nNa parte inferior da tela, deslize o dedo para o lado até a palavra Vídeo ficar destacada em amarelo ou branco.",
          "3. Posicione o celular com firmeza 📐.\nSegure o aparelho com as duas mãos para evitar que o vídeo fique tremido.\n",
          "• Se for enviar no WhatsApp ou YouTube, prefira gravar com o celular deitado 📲 (na horizontal).\n",
          "• Se for para o Instagram ou TikTok, mantenha o celular em pé 📱 (na vertical).",
          "4. Inicie a gravação 🔴.\nToque no botão redondo vermelho no centro da tela. Você verá um contador de tempo começar a rodar na parte superior da tela (ex: 00:01), indicando que o vídeo está sendo gravado.",
          "5. Finalize e salve a gravação ⏹️.\nQuando terminar de falar ou filmar, toque novamente no botão vermelho (ou quadrado) no centro da tela. O vídeo será salvo automaticamente na Galeria ou no aplicativo Fotos 🖼️ do seu celular.",
          "⭐ Dicas para o vídeo ficar excelente: \n",
          "💡 Procure por luz: Grave de frente para uma janela ou em um local bem iluminado. Evite ficar de costas para a luz, caso contrário seu rosto ficará escuro.\n",
          "🔇 Cuidado com o barulho: Grave em um local silencioso, longe de televisores ligados ou vento forte, para que sua voz saia bem nítida.\n",
          "🧼 Limpe a lente: Antes de gravar, passe um pano macio ou a barra da camisa na lente da câmera para retirar marcas de dedo e poeira.",
          "Para saber se a gravação deu certo, abra a Galeria 🖼️ do celular, toque no vídeo salvo e pressione o botão de Play ▶️ (triângulo) para assistir com som! 🔊",
        ],
      },
      {
        titulo: "Encontrando suas fotos",
        descricao: "Onde as fotos ficam guardadas",
        paragrafos: [
          "Encontrar aquela foto especial de uma pessoa querida, de uma viagem ou de um documento é muito fácil. O seu celular guarda todas as imagens organizadas em um só lugar! Siga os passos abaixo:",
          "1.Procure o aplicativo da Galeria ou Fotos 📱:",
          "Na tela inicial do seu celular, procure por um ícone chamado Galeria (geralmente tem o desenho de uma flor ou paisagem) ou Fotos (um catavento colorido). Toque nele uma vez para abrir.",
          "2.Entenda a organização por datas 📅:",
          "Ao abrir o aplicativo, as fotos aparecem organizadas da mais recente para a mais antiga. Deslize o dedo pela tela de baixo para cima para voltar no tempo e ver fotos antigas.",
          "3.Procure pelos Álbuns ou Pastas 📁:",
          "Na parte inferior ou superior da tela, toque na opção Álbuns ou Pastas. As fotos ficam separadas em categorias para facilitar:",
          "Câmera: Fotos que você mesmo tirou com o celular.",
          "WhatsApp: Fotos e imagens que seus amigos e familiares enviaram para você.",
          "Capturas de tela (Screenshots): Fotos tiradas da própria tela do celular.",
          "4.Use a Lupa de Pesquisa 🔍:",
          "Se estiver difícil achar uma foto antiga, toque no ícone da Lupa (normalmente no topo da tela). Você pode digitar palavras-chave para o celular procurar sozinho, como: \"Flores\", \"Praia\", \"Aniversário\" ou até a cidade onde esteve.",
          "Dicas para Não Perder Nenhuma Foto ⭐",
          "Marque como Favorita ❤️: Viu uma foto que amou? Toque no ícone de coração ou estrela na foto. Ela vai direto para uma pasta especial chamada \"Favoritas\", facilitando achar depois.",
          "Crie Álbuns Próprios 📂: Você pode criar uma pasta só para \"Aniversários\" ou \"Receitas\" selecionando as fotos e escolhendo a opção \"Mover para o álbum\".",
          "Lixeira para Reciclar 🗑️: Apagou uma foto sem querer? Não se preocupe! Ela vai para a Lixeira e fica guardada por 30 dias antes de sumir de vez. Dá tempo de restaurar!",
          "Para abrir qualquer foto em tamanho grande e ver todos os detalhes, basta dar um toque rápido em cima dela! 🔎",
        ],
      },
      {
        titulo: "Enviando uma foto",
        descricao: "Compartilhando uma foto com alguém",
        paragrafos: [
          "Compartilhar fotos com a família e os amigos é uma forma incrível de se manter por perto! Veja como enviar uma imagem rápida e com segurança:",
          "1.Abra a conversa desejada 💬:",
          "Abra o WhatsApp e toque na conversa da pessoa ou do grupo para quem você deseja enviar a foto.",
          "2.Toque no ícone do Clipe ou Câmera 📎:",
          "Na parte inferior da tela, onde você digita as mensagens:",
          "Toque no Clipe de papel 📎 (ou no botão +) para escolher uma foto que já está guardada no seu celular.",
          "Ou toque na Câmera 📷 para tirar uma foto nova na mesma hora.",
          "3.Escolha a opção Galeria ou Fotos 🖼️:",
          "Se escolheu o clipe, toque na opção Galeria (ou Fotos). Procure a imagem que deseja mandar e dê um toque rápido sobre ela.",
          "4.Adicione uma legenda, se quiser ✏️:",
          "A foto vai aparecer na tela inteira. Na parte de baixo, você pode tocar em \"Adicionar legenda\" para escrever um recado ou uma mensagem carinhosa sobre aquela foto.",
          "5.Toque no botão de Enviar 🚀:",
          "Para finalizar, toque no botão verde (ou azul) com o desenho de um aviaozinho de papel ou seta no canto inferior direito. Pronto, sua foto foi enviada!",
          "Dicas Importantes para o Envio ⭐",
          "Envie várias fotos de uma vez 📚: Na Galeria, você pode segurar o dedo sobre a primeira foto e depois tocar em outras para selecionar várias antes de enviar.",
          "Cuidado ao tirar foto na hora 📸: Lembre-se de conferir se a foto não ficou tremida ou escura antes de clicar no botão de enviar.",
          "Apagar para todos 🗑️: Enviou a foto errada por engano? Mantenha o dedo pressionado em cima da foto enviada, toque no ícone da Lixeira e escolha a opção \"Apagar para todos\".",
          "Para confirmar se a foto foi recebida, observe o ícone ao lado dela: os dois riscos azuis (✔️✔️) indicam que a pessoa já viu sua foto! 🟢",
        ],
      },
    ],
  },
  {
    numero: 4,
    titulo: "Internet com segurança",
    descricao: "Usar a internet e reconhecer golpes",
    temas: [
      {
        titulo: "Pesquisando na internet",
        descricao: "Encontrando uma informação com segurança",
        paragrafos: [
          "Encontrar receitas, notícias ou tirar dúvidas na internet é rápido e muito útil. Saber como pesquisar de forma segura ajuda a evitar sites falsos e vírus. Siga os passos abaixo:",
          "1.Abra o navegador da internet 🔍:",
          "Procure no seu celular pelo aplicativo do Google Chrome (ícone redondo com as cores vermelha, amarela, verde e azul) ou Safari (ícone de bússola azul) e toque para abrir.",
          "2.Digite o que deseja na barra de pesquisa ✍️:",
          "Toque na barra retangular no meio ou no topo da tela e digite palavras simples sobre o que procura (exemplo: \"receita de bolo de fubá\" ou \"horário do posto de saúde\").",
          "3.Confira os resultados com atenção 👀:",
          "Após tocar no botão de pesquisar (ou na lupa do teclado), aparecerá uma lista de opções. Leia os títulos e os pequenos textos explicativos abaixo de cada um antes de clicar.",
          "4.Procure pelo cadeado de segurança 🔒:",
          "Ao tocar em um site para abrir, olhe para a parte superior da tela (ao lado do endereço do site). Certifique-se de que existe o ícone de um cadeado fechado 🔒, o que indica que a sua conexão com aquele site é segura.",
          "Dicas de Segurança ao Pesquisar ⭐",
          "Evite clicar em anúncios chamativos ⚠️: As primeiras opções da pesquisa costumam ter a palavra \"Patrocinado\" ou \"Anúncio\". Dê preferência aos resultados que aparecem logo abaixo, sem essa marcação.",
          "Cuidado com promessas exageradas 🎁: Se a pesquisa mostrar anúncios de \"prêmios grátis\", \"produtos com 90% de desconto\" ou \"teste de saúde milagroso\", não clique. Geralmente são enganações.",
          "Não informe dados pessoais 🛑: Pesquisas comuns não pedem seu CPF, número do cartão de crédito ou senhas. Se algum site pedir essas informações logo na entrada, feche a página imediatamente.",
          "Para voltar à página inicial de pesquisas a qualquer momento, basta tocar no ícone de Casa 🏠 no navegador ou digitar novamente o que procura! 💡",
        ],
      },
      {
        titulo: "Mensagens de golpe",
        descricao: "Reconhecendo uma mensagem suspeita",
        paragrafos: [
          "Infelizmente, golpistas usam mensagens de texto, WhatsApp e e-mails para tentar enganar as pessoas. Saber identificar os sinais de um golpe é o passo mais importante para navegar na internet com total tranquilidade!",
          "1.Desconfie de pedidos urgentes de dinheiro 💸:",
          "Se receber uma mensagem de um parente ou amigo pedindo dinheiro emprestado ou pagamento de conta via PIX com urgência — principalmente vinda de um número novo —, não pague. Ligue para a pessoa no número antigo para confirmar.",
          "2.Fique atento a links estranhos ou desconhecidos 🔗:",
          "Mensagens com frases como \"Clique aqui para ver suas fotos\", \"Seu nome está no Serasa\" ou \"Você ganhou um prêmio\" acompanhadas de um link (endereço de site) são quase sempre falsas. Nunca toque no link.",
          "3.Identifique ofertas de prêmios e facilidades 🎁:",
          "Bancos, lojas e órgãos do governo não enviam mensagens oferecendo prêmios surpresa, sorteios em que você não se inscreveu ou empréstimos com facilidades exageradas. Se parecer bom demais para ser verdade, é golpe.",
          "4.Verifique se há ameaças de bloqueio de conta ⚠️:",
          "Golpistas costumam assustar as vítimas dizendo que a conta do banco, o cartão ou o WhatsApp serão \"bloqueados nas próximas 2 horas\" se você não clicar em um link. Respire fundo e não aja por impulso.",
          "5.Bloqueie e denuncie o número suspeito 🚫:",
          "Caso receba uma mensagem estranha de um número desconhecido, toque no nome/número no topo da conversa e escolha as opções Bloquear e Denunciar. Assim, o número não consegue mais entrar em contato.",
          "Dicas de Ouro para a sua Segurança ⭐",
          "Bancos não pedem senhas por mensagem 🏦: Nenhum banco ou empresa séria vai mandar mensagem pedindo sua senha, o código de verificação do WhatsApp ou o número do seu cartão.",
          "Nunca compartilhe códigos que chegaram por SMS 📲: Se chegar um código numérico no seu celular por SMS, não passe para ninguém. Ele é a chave para acessar o seu aplicativo.",
          "Mantenha a calma e converse com alguém 🤝: Na dúvida sobre uma mensagem estranha, mostre para um familiar, amigo ou vizinho de confiança antes de tomar qualquer atitude.",
          "Lembre-se: em caso de dúvida, não clique em nada e não responda! Apagar a mensagem é sempre a escolha mais segura. 🛡️",
        ],
      },
      {
        titulo: "Ligações de golpe",
        descricao: "Reconhecendo uma ligação suspeita",
        paragrafos: [
          "Receber chamadas de números desconhecidos é muito comum, mas algumas delas são tentativas de golpe. Saber identificar os sinais de uma ligação suspeita ajuda você a desligar a chamada sem medo e proteger seus dados!",
          "1.Desconfie de ligações dizendo ser do banco 🏦:",
          "Se a ligação disser que é do seu banco informando sobre uma \"compra suspeita no cartão\" ou \"transferência pendente\", tome cuidado. Golpistas usam gravações prontas e tom de urgência para assustar.",
          "2.Fique atento ao golpe do falso sequestro 🚨:",
          "Caso alguém ligue chorando ou gritando dizendo que sequestrou um familiar e peça dinheiro imediato, mantenha a calma. Desligue o telefone imediatamente e ligue direto para o seu parente para checar se ele está bem.",
          "3.Nunca informe senhas ou códigos por telefone 🔐:",
          "Atendentes reais de bancos ou empresas nunca pedem sua senha, o código do cartão de crédito ou os números de confirmação que chegam por SMS no seu celular. Se pedirem, desligue na hora.",
          "4.Recuse pedidos para instalar aplicativos 📲:",
          "Se o visitante da ligação pedir para você baixar um aplicativo de \"segurança\" ou \"suporte técnico\" no celular, recuse. Isso serve para o golpista mexer no seu aparelho à distância.",
          "5.Desligue e faça o retorno você mesmo ☎️:",
          "Ficou em dúvida se a ligação era verdadeira? Desligue o telefone, pegue o seu cartão de banco, veja o número oficial impresso no verso dele e faça uma chamada por conta própria.",
          "Dicas de Ouro para a sua Segurança ⭐",
          "Não confirme seus dados pessoais 🗣️: Se a pessoa perguntar \"Com quem estou falando?\" ou \"Qual o seu CPF?\", não responda. Pergunta primeiro quem está ligando e de qual empresa.",
          "Cuidado com chamadas com \"DDD\" distante 📍: Chamadas frequentes de outros estados ou números muito estranhos podem ser bloqueadas para evitar incômodo.",
          "Bloqueie o número no celular 🚫: Após desligar uma chamada suspeita, vá no histórico de chamadas do celular, toque no número desconhecido e selecione a opção Bloquear contato.",
          "Lembre-se: desligar a chamada na dúvida não é falta de educação, é uma atitude de proteção! 🛡️",
        ],
      },
            {
        titulo: "Criando uma senha segura",
        descricao: "Uma senha forte e fácil de lembrar",
        paragrafos: [
          "Criar uma senha forte é a melhor maneira de proteger seus aplicativos, conversas e conta bancária na internet. Com um truque simples, você cria uma senha difícil para os golpistas, mas fácil de guardar na memória!",
          "1.Pense em uma frase que você gosta 🧠:",
          "Em vez de usar uma palavra só, pense em uma frase fácil de lembrar, como uma música, um ditado ou algo da sua rotina. Exemplo: \"O café da manhã é sempre muito gostoso!\"",
          "2.Pegue as primeiras letras de cada palavra 🔤:",
          "Junte a primeira letra de cada palavra da frase. Usando o exemplo acima (O café da manhã é sempre muito gostoso!), ficamos com a sequência de letras: Ocdm3smg",
          "3.Misture letras maiúsculas e minúsculas 🔠:",
          "Coloque algumas letras em maiúsculo para reforçar a proteção. Exemplo: OcDm3SmG",
          "4.Adicione números e um símbolo especial 🔢:",
          "Para deixar a senha imbatível, coloque um ano, um número marcante ou um símbolo (como #, @ ou !) no final. Exemplo: OcDm3SmG#2026",
          "5.Guarde sua senha em um local seguro 📝:",
          "Anote sua senha em um caderninho físico guardado em um local seguro na sua casa. Evite guardar senhas em papéis soltos ou na capinha do celular.",
          "Dicas de Ouro para a sua Segurança ⭐",
          "Evite dados pessoais óbvios 🚫: Não use sua data de nascimento, seu nome, \"123456\" ou a palavra \"senha\". Golpistas testam essas combinações primeiro.",
          "Não use a mesma senha para tudo 🔑: Crie senhas levemente diferentes para o e-mail, para as redes sociais e para o banco. Se descobrir uma, as outras continuam protegidas.",
          "Nunca compartilhe sua senha 🛑: Nem mesmo com pessoas que dizem trabalhar no banco ou em lojas. A sua senha é pessoal e secreta.",
          "Sua senha é a chave da sua casa digital: mantendo ela bem guardada, seus dados ficam protegidos e seguros! 🛡️",
        ],
      },
    ],
  },
  {
    numero: 5,
    titulo: "Aplicativos do dia a dia",
    descricao: "Banco, farmácia e transporte pelo celular",
    temas: [
     {
        titulo: "Aplicativo do banco",
        descricao: "Usando o banco pelo celular com segurança",
        paragrafos: [
          "Acessar o banco pelo celular traz muita praticidade para consultar saldos, pagar contas e fazer transferências sem precisar sair de casa. Acompanhe o passo a passo para usar os recursos bancários com facilidade e proteção!",
          "1.Baixe o aplicativo oficial do seu banco 📲:",
          "Abra a loja de aplicativos do celular (Google Play Store no Android ou App Store no iPhone), digite o nome exato do seu banco e verifique se o desenvolvedor é o próprio banco antes de tocar em Baixar ou Instalar.",
          "2.Cadastre sua senha de acesso e biometria 🔐:",
          "Na primeira vez que abrir o aplicativo, siga as orientações para cadastrar sua conta. Se o seu celular tiver leitor de digitais ou reconhecimento facial, ative a biometria: isso permite entrar no aplicativo de forma mais rápida e segura.",
          "3.Consulte saldos e extratos de forma simples 👁️:",
          "Na tela principal do aplicativo, toque no ícone do olho (ou na opção \"Mostrar saldo\") para ver quanto dinheiro há na conta. Deslize a tela para baixo para visualizar o extrato com todas as suas movimentações recentes.",
          "4.Faça pagamentos de boletos com a câmera 📷:",
          "Para pagar uma conta de água, luz ou boleto, vá na opção Pagar e escolha Ler código de barras. Aponte a câmera do celular para o código de barras impresso na conta e confirme o valor na tela antes de digitar sua senha.",
          "5.Saia do aplicativo ao terminar 🚪:",
          "Quando concluir o que precisava fazer, nunca feche a tela de uma vez. Procure o botão Sair (ou o ícone de uma porta/cadeado) para encerrar sua sessão bancária com total segurança.",
          "Dicas de Ouro para a sua Segurança ⭐",
          "Não anote senhas no celular 🚫: Nunca salve suas senhas bancárias em notas do celular, no WhatsApp ou na capinha do aparelho.",
          "Nunca use o aplicativo em redes Wi-Fi públicas 📶: Acesse o banco usando a sua rede de internet móvel (4G/5G) ou o Wi-Fi da sua própria casa. Redes de praças, shoppings ou ônibus podem ser inseguras.",
          "Cuidado com quem olha sua tela 👀: Ao digitar senhas em locais públicos ou no transporte, incline o aparelho de forma que outras pessoas ao lado não consigam ver os números digitados.",
          "Usar o aplicativo do banco é simples e seguro quando você mantém suas senhas protegidas e cuida do seu aparelho! 🛡️",
        ],
      },
      {
        titulo: "Consultas e remédios",
        descricao: "Marcando consulta ou pedindo remédio",
        paragrafos: [
          "Usar o celular para cuidar da saúde economiza tempo e evita filas. Hoje em dia, você pode agendar consultas médicas e pedir medicamentos na farmácia sem sair de casa. Siga o passo a passo para utilizar esses serviços de forma simples e segura:",
          "1.Baixe o aplicativo do seu posto, convênio ou farmácia 📲:",
          "Abra a loja de aplicativos (Google Play Store ou App Store) e busque pelo aplicativo do seu plano de saúde, do SUS (como o Meu SUS Digital) ou da sua farmácia de preferência.",
          "2.Para consultas: escolha a especialidade e o horário 🩺:",
          "No aplicativo do convênio ou do posto, toque em Agendar Consulta. Escolha o médico ou a especialidade (ex: Cardiologista ou Clínico Geral), selecione o dia e o horário que preferir e confirme o agendamento.",
          "3.Para remédios: envie a foto da receita para a farmácia 📄:",
          "Muitas farmácias atendem pelo WhatsApp. Adicione o número oficial da farmácia, abra a conversa e envie uma foto bem nítida da sua receita médica para solicitar o orçamento e a entrega em casa.",
          "4.Confira os valores e a forma de entrega 🚚:",
          "No aplicativo da farmácia ou no WhatsApp, verifique o preço dos remédios, escolha se prefere pagar na entrega (em dinheiro ou maquininha de cartão) e informe o seu endereço completo com ponto de referência.",
          "5.Acompanhe a confirmação no seu celular 🔔:",
          "Após concluir o pedido ou o agendamento, você receberá uma mensagem de confirmação na tela ou pelo WhatsApp com a data da consulta ou o horário em que o remédio vai chegar.",
          "Dicas de Ouro para Cuidados com a Saúde ⭐",
          "Mantenha a receita em local bem iluminado 💡: Ao tirar foto da receita para mandar à farmácia, certifique-se de que a foto não ficou embaçada e que o nome do remédio e a dosagem estão fáceis de ler.",
          "Programe alarmes para os remédios ⏰: Use o aplicativo de Relógio/Alarme do próprio celular para colocar despertadores nos horários exatos de tomar cada medicamento ao longo do dia.",
          "Cuidado com mensagens de remédios milagrosos 🛑: Nunca compre medicamentos ou tratamentos anunciados em propagandas suspeitas na internet sem antes conversar com o seu médico de confiança.",
          "Cuidar da sua saúde pelo celular garante mais conforto na sua rotina e facilidade no seu dia a dia! 🏥",
        ],
      },
      {
        titulo: "Chamando um carro",
        descricao: "Pedindo uma corrida pelo aplicativo",
        paragrafos: [
          "Usar aplicativos de transporte pelo celular permite que você se locomova pela cidade com conforto, sem precisar esperar no ponto de ônibus ou procurar um ponto de táxi. Acompanhe o passo a passo para pedir sua viagem com tranquilidade:",
          "1.Abra o aplicativo de transporte 📲:",
          "Procure no seu celular o ícone do aplicativo de sua preferência (como Uber ou 99) e toque nele uma vez para abrir. Lembre-se de deixar a Localização (GPS) do celular ligada.",
          "2.Digite o endereço para onde você quer ir 📍:",
          "Toque na barra onde está escrito \"Para onde?\" ou \"Para onde vamos?\". Digite o nome da rua e o número do local para onde deseja ir (exemplo: \"Rua das Flores, 123\" ou o nome de um hospital/shopping).",
          "3.Confira o ponto de partida e o valor da corrida 💰:",
          "O aplicativo vai mostrar o local onde você está agora e os valores para cada tipo de viagem (como UberX ou 99Pop). Escolha a opção que preferir e verifique a forma de pagamento (dinheiro, cartão no app ou PIX).",
          "4.Confirme a viagem e aguarde o motorista 🚗:",
          "Toque no botão verde ou preto escrito Confirmar ou Solicitar. O aplicativo vai procurar um motorista próximo. Na tela, aparecerá a foto do motorista, a cor e a placa do carro, além do tempo que ele vai demorar para chegar.",
          "5.Confera a placa antes de entrar no carro 👁️:",
          "Quando o carro encostar no local onde você está, olhe a placa do veículo e o modelo do carro para ter certeza de que é o mesmo que aparece na tela do seu celular.",
          "Dicas de Ouro para a sua Segurança ⭐",
          "Pergunte o nome do motorista antes de entrar 🗣️: Ao abrir a porta, pergunte \"Para quem é a corrida?\" ou \"Qual é o seu nome?\" para confirmar que é o motorista certo enviado pelo aplicativo.",
          "Aguarde em um local seguro e bem iluminado 💡: Espere o carro chegar dentro de casa, na portaria do prédio ou em um local movimentado na calçada, sem ficar com o celular exposto na mão.",
          "Compartilhe o trajeto com a família 📲: Dentro do aplicativo, você pode clicar na opção \"Compartilhar viagem\" para mandar o mapa do seu percurso em tempo real para um filho ou amigo pelo WhatsApp.",
          "Ao chegar ao seu destino, verifique se não esqueceu nenhum pertence no banco traseiro antes de fechar a porta! 🏁",
        ],
      },
      {
        titulo: "Horário do ônibus",
        descricao: "Vendo quando o ônibus vai chegar",
        paragrafos: [
          "Consultar o horário e o trajeto do ônibus pelo celular evita esperas longas no ponto e ajuda você a planejar seus passeios com mais conforto. Acompanhe o passo a passo para conferir os horários em tempo real:",
          "1.Abra o aplicativo de mapas ou transporte 📱:",
          "Procure no celular o aplicativo do Google Maps (ícone de um pino colorido) ou um aplicativo de transporte da sua cidade (como o Cittamobi ou Moovit) e toque para abrir.",
          "2.Digite o endereço para onde você quer ir 📍:",
          "Na barra de pesquisa no topo da tela, digite o local de destino (exemplo: \"Praça da Matriz\" ou o nome da rua) e toque na lupa do teclado.",
          "3.Escolha a opção de transporte público 🚏:",
          "Toque no botão Rotas ou Como chegar. Em seguida, procure na parte superior da tela pelo ícone de um ônibus/trem 🚌 e toque nele para ver os caminhos de transporte público.",
          "4.Veja os horários e a linha ideal ⏰:",
          "O aplicativo vai mostrar o número da linha do ônibus, o nome do ponto mais próximo de você e a estimativa de quantos minutos faltam para ele passar.",
          "5.Acompanhe o percurso no mapa 🗺️:",
          "Ao escolher a linha desejada, toque em Iniciar. O mapa vai te orientar a andar até o ponto de ônibus e avisará quantas paradas faltam para você descer no local certo.",
          "Dicas de Ouro para a sua Segurança ⭐",
          "Deixe a Localização (GPS) ligada 📍: Para o aplicativo saber exatamente em qual ponto de ônibus você está, mantenha a função de localização ativada nas configurações do celular.",
          "Guarde o celular ao esperar no ponto 🎒: Após conferir quantos minutos faltam para o ônibus chegar, guarde o aparelho no bolso ou na bolsa enquanto aguarda na calçada.",
          "Peça ajuda se necessário 🗣️: Na dúvida sobre o destino do ônibus, ao embarcar, confirme sempre com o motorista ou cobrador perguntando se o veículo passa pelo local desejado.",
          "Saber a hora exata do transporte facilita sua rotina e deixa seus deslocamentos pela cidade muito mais tranquilos! 🚏",
        ],
      },
    ],
  },
];
